### PR TITLE
Declared support for Dart 2 and updated to latest standards

### PR DESCRIPTION
**Pull request by pulyaevskiy**
Any chance this can be published some time soon?

### CODE REVIEW

**Comment by noordawod** [comment]
Actually, this will fix a host of problems in many other libraries that rely on RSA/PKCS, would love to see it merged in asap. Dart 2 is moving at incredible speeds, hope you guys will have time to merge it sometime soon.

Thanks a bunch for the PR @pulyaevskiy 👍

**Comment by pulyaevskiy** [comment]
Since this is blocking https://github.com/corsac-dart/jwt/issues/1 I'll go ahead and switch to local copy of this lib in my JWT package. When this is merged and published I'll switch back to the hosted version.

@amaurel 
Let me know if you have any concerns about this.

**Comment by noordawod** [comment]
Too bad this is still undone...

**Comment by amaurel** [comment]
Sorry for the delay.

**Comment by amaurel** [comment]
Thanks for the fix ...

**Comment by noordawod** [comment]
@pulyaevskiy good news!

**Comment by pulyaevskiy** [comment]
Great, thanks! Still need a new Pub version though? 
https://pub.dartlang.org/packages/rsa_pkcs

**Pull request merged**
