### PR TITLE
Add nnbd support

### LINKED ISSUE #14: NNBD support
Are there any plans for supporting NNBD? (that would mainly mean to bump crypto to 3.0.0 and asn1lib to 0.9.0 and change some types here and there)

### PR DESCRIPTION
**Pull request by augustozanellato**
closes #14

### CODE REVIEW

**Comment by nilsreichardt** [comment]
@amaurel Can you review this PR?

**Comment by MisterJimson** [comment]
Also looking for this to be reviewed :)

**Comment by Jjagg** [comment]
@amaurel Is there anything we can do to help get this merged?

**Comment by 0biWanKenobi** [comment]
Last roadblock to [allow null safety](https://github.com/corsac-dart/jwt/pull/21) on corsac_jwt, looking forward for this to be merged

**Pull request merged**
