### PR TITLE
Bump asn1lib to stable nnbd and package version to 2.0.0

### PR DESCRIPTION
**Pull request by augustozanellato**
Should be the last blocker before stable nnbd support can be published to pub.dev

### CODE REVIEW

**Comment by amaurel** [comment]
Let's publish this version.

**Comment by amaurel** [comment]
Do we need pre-release constraint on sdk ?
environment:
  sdk: ">=2.12.0-0 <3.0.0"

**Comment by amaurel** [comment]
Shoudn't it be 
environment:
sdk: ">=2.12.0 <3.0.0"

**Comment by augustozanellato** [comment]
> Do we need pre-release constraint on sdk ?
> environment:
> sdk: ">=2.12.0-0 <3.0.0"

We can relax to `>=2.12.0 <3.0.0` because now 2.12.0 has been released

**Pull request merged**
